### PR TITLE
Added UserInput for Nickname and Confirmation Modal with basic styling

### PR DESCRIPTION
**Pull request by lxyhan**
Created a new page UserInfo for the form, redirects to /next-page after it is filled out.

### CODE REVIEW

**Review by Divyanshuoft — DISMISSED** [review]
LGTM

**Review by Ron-Madan — CHANGES_REQUESTED** [review]
As per recent announcement, the phone number verification must be abandoned. As such, you will have to modify your code as per the updated ticket description. This entails removing the phone number portion and adding a confirmation box for the selected nickname. Thank you for your understanding.

**Comment by Ron-Madan** [comment]
LGTM

**Review by lxyhan — COMMENTED** [review]
Reviewed.

**Review by Ron-Madan — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
